load("@onedal//dev/bazel:dal.bzl", "dal_module")

package(default_visibility = ["//visibility:public"])

dal_module(
    name = "triangle_counting_backend_common",
    auto_deps = False,
    srcs = [],
    hdrs = [],
    deps = [
        "@onedal//cpp/oneapi/dal/algo/triangle_counting:common",
        "@onedal//cpp/oneapi/dal/algo/triangle_counting:vertex_ranking_types",
        "@onedal//cpp/oneapi/dal/backend:common",
    ],
)
